server:
  port: 8683
  servlet:
    context-path: /data-tier

management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,beans,heapdump,threaddump"

spring:
  #  r2dbc:
#    url: r2dbc:postgresql://somehostname:someport/databasename
#    username: postgres
#    password: postgres
#  data:
#    r2dbc:
#      repositories:
#        enabled: false
  datasource:
    url: jdbc:tc:postgresql://somehostname:someport/databasename
    username: postgres
    password: postgres
    initialization-mode: never
  jpa:
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:/db/migration
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
#    baseline-on-migrate: true
