version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: library/postgres:13.2-alpine
    environment:
      POSTGRES_DB: galaxy_sandbox
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 1G
        reservations:
          cpus: '0.05'
          memory: 128M