version: '2.2'

services:
  discovery:
    image: localhost/galaxy-sandbox/eureka-server:latest
    restart: on-failure
    ports:
      - "8769:8769"
    volumes:
      - /tmp
    mem_limit: 320m
    mem_reservation: 64m
    environment:
      - JAVA_OPTS=
        -Xms256m
        -Xmx256m
    network_mode: host
  rabbitmq:
    image: rabbitmq:3.8.14-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq:rw
      - ./rabbitmq/log/:/var/log/rabbitmq
      - ./rabbitmq/definitions.json:/opt/definitions.json:ro
      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
    network_mode: host
    mem_limit: 256m
    mem_reservation: 64m
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
  event-consumer:
    depends_on:
      discovery:
         condition: service_started
      rabbitmq:
        condition: service_healthy
    image: localhost/galaxy-sandbox/event-consumer:latest
    restart: on-failure
    ports:
      - "8682:8682"
    mem_limit: 380m
    mem_reservation: 64m
    environment:
        - JAVA_OPTS=
          -Xms256m
          -Xmx320m
        - EUREKA_SERVER=http://127.0.0.1:8769/eureka
    network_mode: host
  event-generator:
      depends_on:
        - event-consumer
      image: localhost/galaxy-sandbox/event-generator:latest
      restart: on-failure
      ports:
        - "8681:8681"
      mem_limit: 380m
      mem_reservation: 64m
      environment:
        - JAVA_OPTS=
          -Xms256m
          -Xmx320m
        - EUREKA_SERVER=http://127.0.0.1:8769/eureka
      network_mode: host
  data-tier:
    depends_on:
      discovery:
        condition: service_started
    image: localhost/galaxy-sandbox/data-tier:latest
    restart: on-failure
    ports:
      - "8683:8683"
    mem_limit: 380m
    mem_reservation: 64m
    environment:
      - JAVA_OPTS=
        -Xms256m
        -Xmx320m
      - EUREKA_SERVER=http://127.0.0.1:8769/eureka
    network_mode: host
