version: '2'

services:
  discovery:
    image: galaxy-sandbox/eureka-server:latest
    restart: on-failure
    ports:
      - "8769:8769"
    volumes:
      - /tmp
    mem_limit: 320m
    mem_reservation: 64m
    environment:
      - JAVA_OPTS=
        -Xms256m
        -Xmx256m
    network_mode: host
  rabbitmq:
    image: rabbitmq:3.8.14-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    network_mode: host
  event-consumer:
    depends_on:
      - discovery
      - rabbitmq
    image: galaxy-sandbox/event-consumer:latest
    restart: on-failure
    ports:
      - "8682:8682"
    mem_limit: 380m
    mem_reservation: 64m
    environment:
        - JAVA_OPTS=
          -Xms256m
          -Xmx320m
        - EUREKA_SERVER=http://127.0.0.1:8769/eureka
    network_mode: host
  event-generator:
      depends_on:
        - discovery
        - rabbitmq
        - event-consumer
      image: galaxy-sandbox/event-generator:latest
      restart: on-failure
      ports:
        - "8681:8681"
      mem_limit: 380m
      mem_reservation: 64m
      environment:
        - JAVA_OPTS=
          -Xms256m
          -Xmx320m
        - EUREKA_SERVER=http://127.0.0.1:8769/eureka
      network_mode: host