server:
  port: 8684

logging:
  level:
    org.springframework.web: DEBUG
    springdoc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,beans,heapdump,threaddump"

spring:
  application:
    name: order-management

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://127.0.0.1:8769/eureka/}
    healthcheck:
      enabled: true

kafka:
  producer:
    broker: 127.0.0.1:9092
    group-id: galaxy-sandbox
