server:
  port: 8769

spring:
  application:
    name: eureka-server

management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,beans,heapdump,threaddump"

eureka:
  instance:
    hostname: localhost
  client:
    enabled: true
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
      enabled: true
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
