server:
  port: 8681

management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,beans,heapdump,threaddump"
  health:
    redis:
      enabled: false

spring:
  application:
    name: event-generator
  mvc:
    log-request-details: true
logging:
  level:
    reactor:
      netty:
        http:
          client: TRACE
    org:
      springframework:
        web:
          reactive:
            function:
              client: TRACE

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://127.0.0.1:8769/eureka/}
    healthcheck:
      enabled: true

generator:
  event-number: 100
  delay-in-ms: 500