INSERT INTO PLANET (NAME, SYSTEM) VALUES ('Earth', 'Solar');
INSERT INTO PLANET (NAME, SYSTEM) VALUES ('Mars', 'Solar');
INSERT INTO PLANET (NAME, SYSTEM) VALUES ('Venus', 'Solar');
INSERT INTO PLANET (NAME, SYSTEM) VALUES ('82 G. Eridani d', '82 G. Eridani');
INSERT INTO PLANET (NAME, SYSTEM) VALUES ('Gliese 12 b', 'Gliese 12');
INSERT INTO PLANET (NAME, SYSTEM) VALUES ('Ross 128 b', 'Ross 128');
INSERT INTO PLANET (NAME, SYSTEM) VALUES ('Gliese 180 c', 'Gliese 180');
INSERT INTO PLANET (NAME, SYSTEM) VALUES ('Gliese 180 d', 'Gliese 180');